// Reference document: https://www.masswerk.at/6502/6502_instruction_set.html

package nes

type OpcodeInfo struct {
	addrMode     AddressMode
	addrModeFunc AddressModeFunc
	inst         Instruction
	instFunc     InstructionFunc
	instSize     uint8
	instCycles   uint8
}

func (cpu *CPU) InitOpcodeTable() {
	cpu.table = [256]OpcodeInfo{
		{modeImpl, cpu.Impl, BRK, cpu.brk, 1, 7}, {modeXInd, cpu.XInd, ORA, cpu.ora, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, ORA, cpu.ora, 2, 3}, {modeZpag, cpu.Zpag, ASL, cpu.asl, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, PHP, cpu.php, 1, 3}, {modeImmd, cpu.Immd, ORA, cpu.ora, 2, 2}, {modeAccu, cpu.Accu, ASL, cpu.asl, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, ORA, cpu.ora, 3, 4}, {modeAbso, cpu.Abso, ASL, cpu.asl, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BPL, cpu.bpl, 2, 2}, {modeIndY, cpu.IndY, ORA, cpu.ora, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, ORA, cpu.ora, 2, 4}, {modeZpgX, cpu.ZpgX, ASL, cpu.asl, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, CLC, cpu.clc, 1, 2}, {modeAbsY, cpu.AbsY, ORA, cpu.ora, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, ORA, cpu.ora, 3, 4}, {modeAbsX, cpu.AbsX, ASL, cpu.asl, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeAbso, cpu.Abso, JSR, cpu.jsr, 3, 6}, {modeXInd, cpu.XInd, AND, cpu.and, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, BIT, cpu.bit, 2, 3}, {modeZpag, cpu.Zpag, AND, cpu.and, 2, 3}, {modeZpag, cpu.Zpag, ROL, cpu.rol, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, PLP, cpu.plp, 1, 4}, {modeImmd, cpu.Immd, AND, cpu.and, 2, 2}, {modeAccu, cpu.Accu, ROL, cpu.rol, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, BIT, cpu.bit, 3, 4}, {modeAbso, cpu.Abso, AND, cpu.and, 3, 4}, {modeAbso, cpu.Abso, ROL, cpu.rol, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BMI, cpu.bmi, 2, 2}, {modeIndY, cpu.IndY, AND, cpu.and, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, AND, cpu.and, 2, 4}, {modeZpgX, cpu.ZpgX, ROL, cpu.rol, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, SEC, cpu.sec, 1, 2}, {modeAbsY, cpu.AbsY, AND, cpu.and, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, AND, cpu.and, 3, 4}, {modeAbsX, cpu.AbsX, ROL, cpu.rol, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeImpl, cpu.Impl, RTI, cpu.rti, 1, 6}, {modeXInd, cpu.XInd, EOR, cpu.eor, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, EOR, cpu.eor, 2, 3}, {modeZpag, cpu.Zpag, LSR, cpu.lsr, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, PHA, cpu.pha, 1, 3}, {modeImmd, cpu.Immd, EOR, cpu.eor, 2, 2}, {modeAccu, cpu.Accu, LSR, cpu.lsr, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, JMP, cpu.jmp, 3, 3}, {modeAbso, cpu.Abso, EOR, cpu.eor, 3, 4}, {modeAbso, cpu.Abso, LSR, cpu.lsr, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BVC, cpu.bvc, 2, 2}, {modeIndY, cpu.IndY, EOR, cpu.eor, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, EOR, cpu.eor, 2, 4}, {modeZpgX, cpu.ZpgX, LSR, cpu.lsr, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, CLI, cpu.cli, 1, 2}, {modeAbsY, cpu.AbsY, EOR, cpu.eor, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, EOR, cpu.eor, 3, 4}, {modeAbsX, cpu.AbsX, LSR, cpu.lsr, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeImpl, cpu.Impl, RTS, cpu.rts, 1, 6}, {modeXInd, cpu.XInd, ADC, cpu.adc, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, ADC, cpu.adc, 2, 3}, {modeZpag, cpu.Zpag, ROR, cpu.ror, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, PLA, cpu.pla, 1, 4}, {modeImmd, cpu.Immd, ADC, cpu.adc, 2, 2}, {modeAccu, cpu.Accu, ROR, cpu.ror, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeIndi, cpu.Indi, JMP, cpu.jmp, 3, 5}, {modeAbso, cpu.Abso, ADC, cpu.adc, 3, 4}, {modeAbso, cpu.Abso, ROR, cpu.ror, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BVS, cpu.bvs, 2, 2}, {modeIndY, cpu.IndY, ADC, cpu.adc, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, ADC, cpu.adc, 2, 4}, {modeZpgX, cpu.ZpgX, ROR, cpu.ror, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, SEI, cpu.sei, 1, 2}, {modeAbsY, cpu.AbsY, ADC, cpu.adc, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, ADC, cpu.adc, 3, 4}, {modeAbsX, cpu.AbsX, ROR, cpu.ror, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeXInd, cpu.XInd, STA, cpu.sta, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, STY, cpu.sty, 2, 3}, {modeZpag, cpu.Zpag, STA, cpu.sta, 2, 3}, {modeZpag, cpu.Zpag, STX, cpu.stx, 2, 3}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, DEY, cpu.dey, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, TXA, cpu.txa, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, STY, cpu.sty, 3, 4}, {modeAbso, cpu.Abso, STA, cpu.sta, 3, 4}, {modeAbso, cpu.Abso, STX, cpu.stx, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BCC, cpu.bcc, 2, 2}, {modeIndY, cpu.IndY, STA, cpu.sta, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, STY, cpu.sty, 2, 4}, {modeZpgX, cpu.ZpgX, STA, cpu.sta, 2, 4}, {modeZpgY, cpu.ZpgY, STX, cpu.stx, 2, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, TYA, cpu.tya, 1, 2}, {modeAbsY, cpu.AbsY, STA, cpu.sta, 3, 5}, {modeImpl, cpu.Impl, TXS, cpu.txs, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, STA, cpu.sta, 3, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeImmd, cpu.Immd, LDY, cpu.ldy, 2, 2}, {modeXInd, cpu.XInd, LDA, cpu.lda, 2, 6}, {modeImmd, cpu.Immd, LDX, cpu.ldx, 2, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, LDY, cpu.ldy, 2, 3}, {modeZpag, cpu.Zpag, LDA, cpu.lda, 2, 3}, {modeZpag, cpu.Zpag, LDX, cpu.ldx, 2, 3}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, TAY, cpu.tay, 1, 2}, {modeImmd, cpu.Immd, LDA, cpu.lda, 2, 2}, {modeImpl, cpu.Impl, TAX, cpu.tax, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, LDY, cpu.ldy, 3, 4}, {modeAbso, cpu.Abso, LDA, cpu.lda, 3, 4}, {modeAbso, cpu.Abso, LDX, cpu.ldx, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BCS, cpu.bcs, 2, 2}, {modeIndY, cpu.IndY, LDA, cpu.lda, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, LDY, cpu.ldy, 2, 4}, {modeZpgX, cpu.ZpgX, LDA, cpu.lda, 2, 4}, {modeZpgY, cpu.ZpgY, LDX, cpu.ldx, 2, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, CLV, cpu.clv, 1, 2}, {modeAbsY, cpu.AbsY, LDA, cpu.lda, 3, 4}, {modeImpl, cpu.Impl, TSX, cpu.tsx, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, LDY, cpu.ldy, 3, 4}, {modeAbsX, cpu.AbsX, LDA, cpu.lda, 3, 4}, {modeAbsY, cpu.AbsY, LDX, cpu.ldx, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeImmd, cpu.Immd, CPY, cpu.cpy, 2, 2}, {modeXInd, cpu.XInd, CMP, cpu.cmp, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, CPY, cpu.cpy, 2, 3}, {modeZpag, cpu.Zpag, CMP, cpu.cmp, 2, 3}, {modeZpag, cpu.Zpag, DEC, cpu.dec, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, INY, cpu.iny, 1, 2}, {modeImmd, cpu.Immd, CMP, cpu.cmp, 2, 2}, {modeImpl, cpu.Impl, DEX, cpu.dex, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, CPY, cpu.cpy, 3, 4}, {modeAbso, cpu.Abso, CMP, cpu.cmp, 3, 4}, {modeAbso, cpu.Abso, DEC, cpu.dec, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BNE, cpu.bne, 2, 2}, {modeIndY, cpu.IndY, CMP, cpu.cmp, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, CMP, cpu.cmp, 2, 4}, {modeZpgX, cpu.ZpgX, DEC, cpu.dec, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, CLD, cpu.cld, 1, 2}, {modeAbsY, cpu.AbsY, CMP, cpu.cmp, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, CMP, cpu.cmp, 3, 4}, {modeAbsX, cpu.AbsX, DEC, cpu.dec, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeImmd, cpu.Immd, CPX, cpu.cpx, 2, 2}, {modeXInd, cpu.XInd, SBC, cpu.sbc, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpag, cpu.Zpag, CPX, cpu.cpx, 2, 3}, {modeZpag, cpu.Zpag, SBC, cpu.sbc, 2, 3}, {modeZpag, cpu.Zpag, INC, cpu.inc, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, INX, cpu.inx, 1, 2}, {modeImmd, cpu.Immd, SBC, cpu.sbc, 2, 2}, {modeImpl, cpu.Impl, NOP, cpu.nop, 1, 2}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbso, cpu.Abso, CPX, cpu.cpx, 3, 4}, {modeAbso, cpu.Abso, SBC, cpu.sbc, 3, 4}, {modeAbso, cpu.Abso, INC, cpu.inc, 3, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
		{modeRela, cpu.Rela, BEQ, cpu.beq, 2, 2}, {modeIndY, cpu.IndY, SBC, cpu.sbc, 2, 5}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeZpgX, cpu.ZpgX, SBC, cpu.sbc, 2, 4}, {modeZpgX, cpu.ZpgX, INC, cpu.inc, 2, 6}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeImpl, cpu.Impl, SED, cpu.sed, 1, 2}, {modeAbsY, cpu.AbsY, SBC, cpu.sbc, 3, 4}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0}, {modeAbsX, cpu.AbsX, SBC, cpu.sbc, 3, 4}, {modeAbsX, cpu.AbsX, INC, cpu.inc, 3, 7}, {modeNone, cpu.None, NOP, cpu.nop, 0, 0},
	}
}
